"""add_discovery_fields

Revision ID: f1abb6002048
Revises: aece2592f078
Create Date: 2026-04-14 00:01:42.168159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1abb6002048'
down_revision: Union[str, Sequence[str], None] = 'aece2592f078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable first
    op.add_column('profiles', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('profiles', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('boost_until', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('profiles', sa.Column('trending_score', sa.Float(), nullable=True))
    op.add_column('profiles', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    
    # 2. Populate defaults for existing rows
    op.execute("UPDATE profiles SET is_featured = FALSE WHERE is_featured IS NULL")
    op.execute("UPDATE profiles SET trending_score = 0.0 WHERE trending_score IS NULL")
    
    # 3. Alter columns to be NOT NULL
    op.alter_column('profiles', 'is_featured', nullable=False)
    op.alter_column('profiles', 'trending_score', nullable=False)

    # 4. Create indices
    op.create_index('ix_profiles_category', 'profiles', ['category'], unique=False)
    op.create_index('ix_profiles_search_vector', 'profiles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_profiles_trending_score', 'profiles', ['trending_score'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_trending_score', table_name='profiles')
    op.drop_index('ix_profiles_search_vector', table_name='profiles', postgresql_using='gin')
    op.drop_index('ix_profiles_category', table_name='profiles')
    op.drop_column('profiles', 'search_vector')
    op.drop_column('profiles', 'trending_score')
    op.drop_column('profiles', 'boost_until')
    op.drop_column('profiles', 'is_featured')
    op.drop_column('profiles', 'category')
    # ### end Alembic commands ###
